app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
    interval-since-last-check: 100
  baseGitHubUrl: https://api.github.com/repos/
  baseStackOverflowUrl: https://api.stackexchange.com/
  baseBotClientUrl: http://localhost:8090
  database-access-type: jpa

retry:
  github:
    type: fixed
    max-attempt: 3
    delay: 10
    codes:
      -500
      -501
      -503
  stackoverflow:
      type: linear
      max-attempt: 3
      delay: 10
      codes:
        -500
        -501
        -503
  bot:
    type: linear
    max-attempt: 3
    delay: 10
    codes:
      -500
      -501
      -503
spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    #url: jdbc:postgresql://postgresql:5437/scrapper
    url: jdbc:postgresql://localhost:5437/scrapper
    username: ${USERNAME}
    password: ${PASSWORD}
    driverClassName: org.postgresql.Driver

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
