app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
    interval-since-last-check: 100
  baseGitHubUrl: https://api.github.com/repos/
  baseStackOverflowUrl: https://api.stackexchange.com/
  baseBotClientUrl: http://localhost:8090

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    #url: jdbc:postgresql://postgresql:5437/scrapper
    url: jdbc:postgresql://localhost:5437/scrapper
    username: ${USERNAME}
    password: ${PASSWORD}
    driverClassName: org.postgresql.Driver

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
