app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
    interval-since-last-check: 100
  baseGitHubUrl: https://api.github.com/repos/
  baseStackOverflowUrl: https://api.stackexchange.com/
  baseBotClientUrl: http://localhost:8090
  database-access-type: jpa
  kafka-topic-name: updates
  use-queue: false

retry:
  github:
    type: fixed
    max-attempt: 3
    delay: 10
    codes: [500, 501, 503]
  stackoverflow:
      type: linear
      max-attempt: 3
      delay: 10
      codes: [500, 501, 503]
  bot:
    type: linear
    max-attempt: 3
    delay: 10
    codes: [500, 501, 503]
spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    #url: jdbc:postgresql://postgresql:5437/scrapper
    url: jdbc:postgresql://localhost:5437/scrapper
    username: ${USERNAME}
    password: ${PASSWORD}
    driverClassName: org.postgresql.Driver
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
      bootstrap-servers: localhost:29092
    bootstrap-servers: localhost:29092

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: .*
      http-status-code: TOO_MANY_REQUESTS
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\" }"
      rate-limits:
        - cache-key: getRemoteAddr()
          bandwidths:
            - capacity: 100000
              time: 1
              unit: hours

management:
  server:
    port: 8800
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
      base-path: /
      path-mapping:
        prometheus: /metrics
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
        application: ${spring.application.name}




springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
