app:
  telegram-token: ${MY_TOKEN}
  baseScrapperClientUrl: http://localhost:8080

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  liquibase:
    enabled: false
  datasource:
    #url: jdbc:postgresql://postgresql:5437/scrapper
    url: jdbc:postgresql://localhost:5437/scrapper
    username: ${USERNAME}
    password: ${PASSWORD}
    driverClassName: org.postgresql.Driver
retry:
  scrapper-retry:
    type: fixed
    max-attempt: 3
    delay: 10
    codes: [500, 501, 503]

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
