package edu.java.configuration;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class SpringDocConfiguration {

    @Bean(name = "org.openapitools.configuration.SpringDocConfiguration.apiInfo")
    OpenAPI apiInfo() {
        return new OpenAPI()
            .info(
                new Info()
                    .title("Scrapper API")
                    .description(
                        "No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)")
                    .contact(
                        new Contact()
                            .name("D-Muscipula")
                            .url("https://github.com/D-Muscipula")
                    )
                    .version("1.0.0")
            );
    }
}
