/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.domain.jooq;

import edu.java.scrapper.domain.jooq.tables.Link;
import edu.java.scrapper.domain.jooq.tables.TgUser;
import edu.java.scrapper.domain.jooq.tables.UsersLinks;
import edu.java.scrapper.domain.jooq.tables.records.LinkRecord;
import edu.java.scrapper.domain.jooq.tables.records.TgUserRecord;
import edu.java.scrapper.domain.jooq.tables.records.UsersLinksRecord;
import javax.annotation.processing.Generated;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LinkRecord> CONSTRAINT_2 =
        Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_2"), new TableField[] {Link.LINK.ID}, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_23 =
        Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_23"), new TableField[] {Link.LINK.URL}, true);
    public static final UniqueKey<TgUserRecord> CONSTRAINT_D = Internal.createUniqueKey(TgUser.TG_USER,
        DSL.name("CONSTRAINT_D"),
        new TableField[] {TgUser.TG_USER.USER_CHAT_ID},
        true
    );
    public static final UniqueKey<TgUserRecord> CONSTRAINT_DA = Internal.createUniqueKey(TgUser.TG_USER,
        DSL.name("CONSTRAINT_DA"),
        new TableField[] {TgUser.TG_USER.USER_CHAT_ID},
        true
    );
    public static final UniqueKey<UsersLinksRecord> CONSTRAINT_AD6 = Internal.createUniqueKey(UsersLinks.USERS_LINKS,
        DSL.name("CONSTRAINT_AD6"),
        new TableField[] {UsersLinks.USERS_LINKS.TG_USER, UsersLinks.USERS_LINKS.LINK},
        true
    );

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<UsersLinksRecord, TgUserRecord> CONSTRAINT_A =
        Internal.createForeignKey(UsersLinks.USERS_LINKS,
            DSL.name("CONSTRAINT_A"),
            new TableField[] {UsersLinks.USERS_LINKS.TG_USER},
            Keys.CONSTRAINT_D,
            new TableField[] {TgUser.TG_USER.USER_CHAT_ID},
            true
        );
    public static final ForeignKey<UsersLinksRecord, LinkRecord> CONSTRAINT_AD =
        Internal.createForeignKey(UsersLinks.USERS_LINKS,
            DSL.name("CONSTRAINT_AD"),
            new TableField[] {UsersLinks.USERS_LINKS.LINK},
            Keys.CONSTRAINT_2,
            new TableField[] {Link.LINK.ID},
            true
        );
}
