/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.domain.jooq;

import edu.java.scrapper.domain.jooq.tables.Link;
import edu.java.scrapper.domain.jooq.tables.TgUser;
import edu.java.scrapper.domain.jooq.tables.UsersLinks;
import javax.annotation.processing.Generated;

/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Tables {

    /**
     * The table <code>LINK</code>.
     */
    public static final Link LINK = Link.LINK;

    /**
     * The table <code>TG_USER</code>.
     */
    public static final TgUser TG_USER = TgUser.TG_USER;

    /**
     * The table <code>USERS_LINKS</code>.
     */
    public static final UsersLinks USERS_LINKS = UsersLinks.USERS_LINKS;
}
